name: Trivy Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          exit-code: 1
          ignore-unfixed: true
          format: 'table'
